[package]
name = "rust"
version = "0.1.0"
authors = ["Javier E. Fajardo <foxtrotzulu94@gmail.com>"]

[dependencies]
rayon = "1.0"
rust-crypto = { git = "https://github.com/niluxv/rust-crypto", branch = "stable_0.2" }
clap = "2"
chrono = "0.4"
